# Generated by Django 2.2.17 on 2020-12-19 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('password', models.BinaryField(max_length=255)),
                ('date_joined', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
